spring.application.name=badwallet-api
server.port=8080

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:badwalletdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate genere et met a jour automatiquement le schema des tables
spring.jpa.hibernate.ddl-auto=update

# Console H2 accessible sur le navigateur via /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

api.pagination.default-page=0
api.pagination.default-size=10
